# Generated by Django 5.2.6 on 2025-09-05 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.BigIntegerField(unique=True)),
                ('event', models.IntegerField()),
                ('finished', models.BooleanField(default=False)),
                ('finished_provisional', models.BooleanField(default=False)),
                ('kickoff_time', models.DateTimeField()),
                ('minutes', models.IntegerField()),
                ('provisional_start_time', models.BooleanField(default=False)),
                ('started', models.BooleanField(default=False)),
                ('team_a', models.IntegerField()),
                ('team_a_score', models.IntegerField()),
                ('team_h', models.IntegerField()),
                ('team_h_score', models.IntegerField()),
                ('stats', models.JSONField()),
                ('team_h_difficulty', models.IntegerField()),
                ('team_a_difficulty', models.IntegerField()),
                ('pulse_id', models.BigIntegerField()),
            ],
        ),
    ]
